CREATE TABLE BATCH_JOB_SEQ
(
    ID_NAME VARCHAR(100) NOT NULL,
    ID_VAL  BIGINT       NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_NAME)
);

INSERT INTO BATCH_JOB_SEQ (ID_NAME, ID_VAL)
VALUES ('BATCH_JOB_SEQ', 0);
